version: '3.8'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - media:/app/media
    networks:
      - default 
    environment:
      DJANGO_SETTINGS_MODULE: "rhizotron.settings.docker"
    depends_on:
      mysqldb:
        condition: service_healthy
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  mysqldb:
    restart: unless-stopped
    image: mysql:8.3
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "passw0rd"
      MYSQL_DATABASE: dev
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  prometheus:
    restart: unless-stopped
    image: bitnami/prometheus:2.51.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - default
  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.3.5
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - default

volumes:
  mysql:
  media:
  grafana:
  prometheus:

networks:
  default: {}
