# Generated by Django 5.0.1 on 2024-02-10 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "segmentation",
            "0007_rename_prediction_mask_picture_alter_mask_image_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mask",
            old_name="image",
            new_name="picture",
        ),
    ]
