# Generated by Django 5.0.1 on 2024-02-10 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segmentation", "0008_rename_image_mask_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mask",
            old_name="mask",
            new_name="image",
        ),
    ]
